#!/usr/bin/make
#
# make fragment for png23d tests

TESTS=square.stl c.stl o.stl s.stl spiral.stl \
	 cube.astl steps.astl plus.astl plusa.astl plusb.astl \
	calcube.stl debian-logo.scad

TESTF=$(addprefix test/, $(TESTS))


check:png23d $(TESTF)

# convert to binary stl
test/%.stl:test/%.png
	./png23d -o stl -w 20 -d 10 $< $@

#convert to ascii stl (cheats by also having 10 levels for these tests)
test/%.astl:test/%.png
	./png23d -l 10 -o astl -w 20 -d 10 $< $@

#convert to smoothed single layer polyhedron scad output
test/%.scad:test/%.png
	./png23d -l 1 -f smooth -o pscad -w 50 -d 4 $< $@


test/calcube.stl:test/calcube.png
	./png23d -f raw -o stl -w 20 -d 10 $< $@

.PHONY: testclean

testclean:
	${RM} $(TESTF)