/*
 * Copyright 2011 Vincent Sanders <vince@kyllikki.org>
 *
 * Licenced under the MIT License,
 *                http://www.opensource.org/licenses/mit-license.php
 *
 * This file is part of png23d.
 *
 * Routines to output in scad polyhedron format
 */

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <assert.h>

#include "option.h"
#include "bitmap.h"
#include "mesh.h"
#include "out_pscad.h"


/* ascii stl outout */
bool output_flat_scad_polyhedron(bitmap *bm, int fd, options *options)
{
    struct mesh *mesh;
    unsigned int ploop;
    unsigned int tloop; /* triangle loop */
    int xoff; /* x offset so 3d model is centered */
    int yoff; /* y offset so 3d model is centered */
    FILE *outf;

    outf = fdopen(dup(fd), "w");

    mesh = new_mesh();
    if (mesh == NULL) {
        fprintf(stderr,"unable to create mesh\n");
        return false;
    }

    debug_mesh_init(mesh, options->meshdebug);

    if (mesh_from_bitmap(mesh, bm, options) == false) {
        fprintf(stderr,"unable to convert bitmap to mesh\n");
        return false;
    }

    if (options->optimise > 0) {
        simplify_mesh(mesh);
    } else {
        index_mesh(mesh);
    }

    xoff = (bm->width / 2);
    yoff = (bm->height / 2);

    fprintf(outf, "// Generated by png2scad\n\n");

    fprintf(outf, "target_width = %f;\n", options->width);
    fprintf(outf, "target_depth = %f;\n\n", options->depth);

    fprintf(outf, "module image(sx,sy,sz) {\n scale([sx, sy, sz]) polyhedron(points = [\n");

    for (ploop = 0; ploop < mesh->pcount; ploop++) {
        fprintf(outf, "[%f,%f,%f],\n", 
                mesh->p[ploop].pnt.x - xoff, 
                mesh->p[ploop].pnt.y + yoff, 
                mesh->p[ploop].pnt.z);
    }

    fprintf(outf, "], triangles = [\n");

    for (tloop = 0; tloop < mesh->fcount; tloop++) {
        fprintf(outf, "[%u,%u,%u],\n",
                mesh->f[tloop].i[0],
                mesh->f[tloop].i[1],
                mesh->f[tloop].i[2] );
    }


    fprintf(outf, "]); }\n\n");

    fprintf(outf, "image_width = %d;\n", bm->width);
    fprintf(outf, "image_height = %d;\n\n", bm->height);

    fprintf(outf, "image(target_width / image_width, target_width / image_width, target_depth);\n");


    free_mesh(mesh);

    fclose(outf);

    return true;
}
